spring.datasource.url=jdbc:postgresql://localhost:5432/security_bank
spring.datasource.username=alejandro
spring.datasource.password=debugueandoideas
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
server.port=8081

# 1. Fuerza a que el script se ejecute SIEMPRE
spring.sql.init.mode=always

# 2. Obliga a que data.sql corra DESPUÉS de que Hibernate valide/cree el esquema
spring.jpa.defer-datasource-initialization=true

# 3. Asegura el comportamiento del ddl (usa update para no borrar otras tablas locales)
spring.jpa.hibernate.ddl-auto=update